AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  notify_hitokuchi

  SAM Template for notify_hitokuchi

Parameters:
  Stage:
    Type: String
    Default: Dev
  SqsUrl:
    Type: String
  HorsesJsonArn:
    Type: String

Resources:
  NotifyHitokuchiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      CodeUri: notify_hitokuchi/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        NotifyHitokuchi:
          Type: Schedule
          Properties:
            Schedule: cron(30 12 * * ? *)
      Environment:
        Variables:
          STAGE:
            Ref: Stage
          SQSURL:
            Fn::ImportValue:
              Ref: SqsUrl
      Policies:
        - Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
              - sts:AssumeRole
              - ssm:GetParameters
              - sqs:SendMessage
            Resource: "*"
        - Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
              - s3:GetObject
            Resource: !Ref HorsesJsonArn
