name: build-and-deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install sam-cli
        run: |
          python -m pip install --upgrade pip
          pip install awscli
          pip install aws-sam-cli
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Build
        run: sam build --use-container
      - name: Deploy
        run: sam deploy --stack-name notify-hitokuchi --s3-bucket ${{ secrets.AWS_SAM_BUCKET_NAME }} --s3-prefix notify-hitokuchi-prod --capabilities CAPABILITY_IAM --parameter-overrides "Stage=Prod"
