name: build-and-deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  id-token: write
  contents: read    # This is required for actions/checkout
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install sam-cli
        run: |
          python -m pip install --upgrade pip
          pip install awscli
          pip install aws-sam-cli
      - name: Install pipenv
        run: python -m pip install pipenv
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: NotifyHitokuchi
          aws-region: ap-northeast-1
      - name: Build
        run: pipenv run build
      - name: Deploy
        if: startsWith(github.ref, 'refs/heads/master')
        run: sam deploy --stack-name notify-hitokuchi --s3-bucket ${{ secrets.AWS_SAM_BUCKET_NAME }} --s3-prefix notify-hitokuchi-prod --capabilities CAPABILITY_IAM --parameter-overrides "Stage=Prod SqsUrl=SlackIncomingWebHookAppProd-QUEUE-URL"
